#!/usr/bin/env bash

function gitClean {
    cd "$1"
    if git status | grep "nothing to commit, working directory clean" > /dev/null
    then
        ERR=1
        COUNT=$((COUNT - 1))
        echo "Uncommited things in '$1'" >> /dev/stderr
    fi
}

ERR=0
COUNT=10
while IFS= read -r REPO
do
    DIR=$(dirname "$REPO")
    gitClean "$DIR"
    [[ "$COUNT" -eq 0 ]] && break
done < <(locate '/home/chris/Programming/*/.git')

exit "$ERR"
