#!/usr/bin/env bash

# Pass in the argument "full" to keep going after a failure
FULL=0
[[ "x$1" = "xfull" ]] && FULL=1

ERR=0
while read -r PROJECT
do
    DIR=""
    for FILE in "$PROJECT"/*.cabal
    do
        DIR=$(dirname "$FILE")
    done
    [[ -n "$DIR" ]] || continue

    if ! (cd "$DIR" && hsConfig)
    then
        ERR=1
        [[ "$FULL" -eq 1 ]] || exit 1
    fi
done < <(my_haskell)

exit "$ERR"
