#!/usr/bin/env bash

function data {
    while read -r PROJECT
    do
        find "$PROJECT" -maxdepth 1 -name "*.cabal"
    done < <(my_haskell)
}

function cached {
    ./helpers/cache.sh "cabal-nixable" < <(data)
}

# Check how we were called
if NAME=$(./helpers/getName.sh "$0")
then
    LINES=$(./helpers/checkNames.sh "$NAME" < <(cached)) || ERR=1
    while read -r LINE
    do
        echo "Trying $LINE"
        DIR=$(dirname "$LINE")
        pushd "$DIR"
        cabal clean
        hsConfig || exit 1
        popd
    done < <(echo "$LINES")
else
    ./helpers/namesMatch.sh "cabal-nixable" < <(cached) || exit 1
fi
