#!/usr/bin/env bash

function isGit {
    (cd "$1"; git rev-parse --show-toplevel 1> /dev/null 2> /dev/null)
}

# Make sure everything in ~/Programming is version controlled
COUNT=10 # Stop early if we find this many unversioned things
ERR=0
while IFS= read -r DIR
do
    # Skip if any check passes
    isGit "$DIR" && continue

    # No check passed, so make a note
    echo "$DIR doesn't seem to be version controlled" >> /dev/stderr
    ERR=1
    COUNT=$(( COUNT - 1 ))
    [[ "$COUNT" -eq 0 ]] && break
done < <(find ~/Programming -type f -exec dirname {} \; | uniq)

pkill find # Prevent dirname spawning over and over
exit "$ERR"
