#!/usr/bin/env bash

# Pass in the argument "full" to keep going after a failure
FULL=0
[[ "x$1" = "xfull" ]] && FULL=1

shopt -s nullglob

function isGit {
    (cd "$1"; git rev-parse --show-toplevel 1> /dev/null 2> /dev/null)
}

function isSvn {
    svn info "$1" 2> /dev/null 1> /dev/null
}

function isDarcs {
    (cd "$1"; darcs show files > /dev/null 2> /dev/null)
}

function isHg {
    hg --cwd "$1" root 2> /dev/null 1> /dev/null
}

function isBzr {
    if bzr check --tree "$1" 2>&1 |
       grep "No working tree found at specified location." > /dev/null
    then
        return 1
    fi
    return 0
}

function isVC {
    isGit "$1" || isSvn "$1" || isDarcs "$1" || isHg "$1" || isBzr "$1"
}

function skip {
    grep -v "Programming/git-html" |
    grep -v "\.git"                |
    grep -v "\.svn"                |
    grep -v "Programming/CIL"      |
    grep -v "Programming/CCOD"     |
    grep -v "Programming/Coq/PACO" |
    grep -v "Programming/CUDA"     |
    grep -v "Programming/Djabberd" |
    grep -v "Programming/repos"    |
    while read -r LINE
    do
        #if [[ $(( RANDOM % 4 )) -eq 0 ]]
        #then
            echo "$LINE"
        #fi
    done
}

FAILS="results/data/git-repos"
function cached {
    mkdir -p results/data

    if [[ -e "$FAILS" ]] && test $(find "$FAILS" -mmin -60)
    then
        cat "$FAILS"
    fi

    # Always include the root
    echo "/home/chris/Programming"
}

# Make sure everything in ~/Programming is version controlled
ERR=0

DIRS=$(cached)
NEW=""
PREV=""
while [[ -n "$DIRS" ]]
do
    while read -r D
    do
        [[ -z "$D" ]] && continue
        for ENTRY in "$D/"*
        do
            [[ -z "$ENTRY" ]] && continue
            if [[ -d "$ENTRY" ]]
            then
                # Skip version-controlled dirs
                if ! isVC "$ENTRY"
                then
                    NEW=$(printf "%s\n%s" "$NEW" "$ENTRY")
                fi
            else
                DN=$(dirname "$ENTRY")

                # Skip any directory we've just seen
                [[ "x$DN" = "x$PREV" ]] && continue
                PREV="$DN"

                # Skip if any check passes
                if ! isVC "$DN"
                then
                    # File is not version controlled
                    echo "$ENTRY doesn't look version controlled" >> /dev/stderr
                    echo "$DN" >> "$FAILS"
                    ERR=1
                    [[ "$FULL" -eq 1 ]] || exit 1
                fi
            fi
        done
    done < <(echo "$DIRS")
    DIRS=$(echo "$NEW" | skip)
    NEW=""
done

exit "$ERR"
