#!/usr/bin/env bash

function cached {
    ./helpers/cache.sh "haskell-builds" < <(my_haskell)
}

function cabalBuild {
    if ! hsConfig
    then
        echo "Couldn't hsConfig in '$DIR'" >> /dev/stderr
        exit 1
    fi
    if ! cabal build
    then
        exit 1
    fi
}

function buildFiles {
    shopt -s nullglob
    ERR=0
    for HS in *.hs *.lhs
    do
        echo "Type-checking '$HS'"
        if ! ghc "$HS" -e 'return ()'
        then
            ERR=1
        fi
    done
    exit "$ERR"
}

if DIR=$(./helpers/nthLine.sh "$0" "haskell-builds")
then
    cd "$DIR"
    if test -n "$(find . -maxdepth 1 -type f -name '*.cabal' -print -quit)"
    then
        echo "Found Cabal file in '$DIR', trying to configure and build project"
        cabalBuild
    else
        echo "No Cabal file in '$DIR', type-checking any individual files"
        buildFiles
    fi
else
    ./helpers/checkCache.sh "haskell-builds" < <(cached)
fi
