#!/usr/bin/env bash

# Pass in the argument "full" to keep going after a failure
FULL=0
[[ "x$1" = "xfull" ]] && FULL=1

ERR=0
while IFS= read -r DIR
do
    cd "$DIR"
    if ! hsConfig
    then
        echo "Couldn't hsConfig in '$DIR'" >> /dev/stderr
        ERR=1
        [[ "$FULL" -eq 1 ]] || exit 1
        continue
    fi
    if ! cabal build
    then
        ERR=1
        [[ "$FULL" -eq 1 ]] || exit 1
    fi
done < <(my_haskell)

exit "$ERR"
