#!/usr/bin/env bash

function data {
    locate -e "/home/chris/Programming/*/hpc_index.html"
}

function cached {
    ./helpers/cache.sh "hpc-coverage" < <(data)
}

# Check how we were called
IDX=$(basename "$0" .hpc)
if [[ "x$IDX" = "xhpc-coverage" ]]
then
    # No index given, check indices match up
    CACHECOUNT=$(cached | wc -l)
    FILECOUNT=$(ls scripts/*.hpc | wc -l)
    if [[ "$CACHECOUNT" -eq "$FILECOUNT" ]]
    then
        echo "Got enough tests to cover hpc counts"
    else
        echo "Have $FILECOUNT test(s) for $CACHECOUNT files" >> /dev/stderr
        exit 1
    fi
else
    file=$(cached | tail -n"$IDX" | head -n1)
    TOTAL='th[contains(text(),"Program Coverage Total")]'
    PERCENT='following-sibling::td[1]/text()'
    RESULT=$(xidel - --extract "//${TOTAL}/${PERCENT}" < "$file" | tr -d '%')
    if ! [[ "$RESULT" -lt "70" ]]
    then
        echo "'$RESULT' coverage for '$file'" >> /dev/stderr
        exit 1
    fi
fi
