#!/usr/bin/env bash

function backups {
    find ~/Programming -name "*~"
    find ~/Programming -name "#*#"
}

function skip {
    grep -v "/git-html/" | grep -v "/isaplanner-code/"
}

ERR=0

while read -r BACKUP
do
    echo "$BACKUP looks like a backup file"
    ERR=1
done < <(backups | skip)

exit "$ERR"
