#!/usr/bin/env bash

# Gitorious.org is gone. Don't try pushing there.

function files {
    # Find .git/config files
    grep -v "/git-html" < <(
        grep -v "/Backups/" < <(
            grep ".git" < <(
                locate -e "/home/chris/*/config")))
}

function cached {
    ./helpers/cache.sh "no-gitorious" < <(files)
}

cached > /dev/null

ERR=0
while read -r CONFIG
do
    grep "gitorious" < "$CONFIG" > /dev/null && {
        ERR=1
        echo "Reference to gitorious found in '$CONFIG'" >> /dev/stderr
    }
done < <(cached)

exit "$ERR"
