#!/usr/bin/env bash

function data {
    locate "render.sh" | grep "/Writing/"
}

function cached {
    ./helpers/cache.sh "render" < <(data)
}

if SCRIPT=$(./helpers/nthLine.sh "$0" "render")
then
    DIR=$(dirname "$SCRIPT")
    if ! (cd "$DIR" && "./render.sh")
    then
        echo "$SCRIPT failed" >> /dev/stderr
        exit 1
    fi
else
    ./helpers/checkCache.sh "render" < <(cached)
fi
