#! /usr/bin/env bash

# Pass in the argument "full" to keep going after a failure
FULL=0
[[ "x$1" = "xfull" ]] && FULL=1

function skip {
    # Skip Python, Haskell and makefiles
    INPUT=$(grep "^#!")
    echo "$INPUT" | grep "python"  ||
    echo "$INPUT" | grep "haskell" ||
    echo "$INPUT" | grep "gnumake"
}

shopt -s nullglob
ERR=0
for script in ~/.tests/*.sh ~/.tests/scripts/* ~/warbo-utilities/system/*
do
    if skip < "$script" > /dev/null
    then
        continue
    fi
    if ! shellcheck -e SC1008 -e SC2001 "$script"
    then
        ERR=1
        [[ "$FULL" -eq 1 ]] || exit 1
    fi
done

exit "$ERR"
