#!/usr/bin/env bash

function fail {
    echo "$1" >> /dev/stderr
    exit 1
}

# Check the sites

[[ -e ~/Writing/STP/sites/stp/2015/10/index.md ]] || fail "2015/10 has no index"

(cd ~/Writing/STP/sites; ./render.sh) || fail "Couldn't render sites"

# Check the talks
[[ -e ~/Writing/STP/talks/2015/10/slides.md ]] || fail "2015/10 has no slides"

(cd ~/Writing/STP/talks; ./render.sh) || fail "Couldn't render talks"
